services:
  db:
    image: mysql:8.1
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: todos
      MYSQL_DATABASE: todos
    ports:
      - "3309:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql